### ISSUE TITLE
Windows Menü durch Klick weiterhin aufrufbar bei deaktivierter Windows-Taste

### ISSUE THREAD

**Issue by zibbozz** [zibbozz/DNAV#17]

**Comment by xHeartInHandx** [comment]
Vllt einfach die komplette Taskleiste ausblenden

**Comment by xHeartInHandx** [comment]
- http://csharphelper.com/blog/2016/02/hide-the-taskbar-and-start-button-in-c/
- https://www.mycsharp.de/wbb2/thread.php?postid=27246
