### ISSUE TITLE
Autostart erweitern: Trojaner kopiert sich an einen festlegbaren Ort und Autostart startet diese Datei

### ISSUE THREAD

**Issue by zibbozz** [zibbozz/DNAV#19]

**Comment by nclskpprs** [comment]
Diese Einträge könnte helfen!
- https://www.codeproject.com/Questions/1033660/Csharp-how-to-copy-executable-to-a-directory
- https://www.c-sharpcorner.com/forums/c-sharp-copy-exe-to-appdata
