### ISSUE TITLE
Funktion: Neue Benutzeraccounts erstellen

### ISSUE THREAD

**Issue by zibbozz** [zibbozz/DNAV#34]

**Comment by nclskpprs** [comment]
Lokales Administratorkonto wird hinzugefügt. Benutzername und Passwort werden als Übergabeparameter angegeben.
Falls eine Version mit Gast Account hinzugefügt werden soll, dann muss dieses Ticket wieder auf ,,in progress'' gestellt werden.

Update:
Funktioniert aktuell nur bei einem deutschen Windows.
